### ISSUE TITLE
Absinthe support

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir-plug#12]
To move from the [snippet](https://docs.appsignal.com/elixir/integrations/absinthe.html) we currently use to something that provides some more data, we’ll add proper Absinthe support. We should be able to implement this directly in appsignal_plug without adding any dependencies.

**Comment by jeffkreeftmeijer** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/search/conversations/16410700030647?q=absinthe&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all

**Comment by Nualadoyle** [comment]
Hello! Just wondering if this will be looked at in the near future? The customer affected is approaching the end of their (extended) trial so checking how long I should extend it for again.

**Comment by jeffkreeftmeijer** [comment]
Closed by https://github.com/appsignal/appsignal-elixir/pull/840.
