### ISSUE TITLE
How to ignore plug endpoints?

### ISSUE THREAD

**Issue by meysammeisam** [appsignal/appsignal-elixir-plug#23]
In a setup like:

```elixir
defmodule AppsignalPlugExample do
  use Plug.Router
  use Appsignal.Plug # <- Add this

  plug :match
  plug :dispatch

  get "/health" do
    send_resp(conn, 200, "hooray!")
  end

  get "/" do
    Appsignal.Transaction.set_action("GET /") # <- Set the action name

    send_resp(conn, 200, "Welcome")
  end
end
```

How the transactions for the `/health` endpoint can be ignored?
We couldn't find anything the docs here:
https://docs.appsignal.com/elixir/1.x/integrations/plug.html#main

**Comment by tombruijn** [comment]
Hi @meysammeisam, You can ignore the actions like `/health` with the `ignore_actions` config option: https://docs.appsignal.com/guides/filter-data/ignore-actions.html

It would probably become something like this in your config:

```elixir
# Example: config/appsignal.exs
config :appsignal, :config,
  ignore_actions: ["GET /health"]
```
(The action name may be different for your app. Check your app data on AppSignal.com to see what name the action you want to ignore is reported as.)

Let us know if you have further questions at support@appsignal.com :)

**Comment by meysammeisam** [comment]
Thanks it seems to be working.
