### ISSUE TITLE
No session data after updating to Appsignal Elixir 2.0

### ISSUE THREAD

**Issue by mbuhot** [appsignal/appsignal-elixir-plug#6]
`Appsignal.Plug` is matching against `true` in the `Plug.Conn.private.plug_session_fetch` field:
https://github.com/appsignal/appsignal-elixir-plug/blob/main/lib/appsignal_plug.ex#L187

It should be matching against `:done`, as it does in `Appsignal.Transaction.set_request_metadata/2`:

https://github.com/appsignal/appsignal-elixir/blob/master/lib/appsignal/transaction.ex#L514

As `:done` is the value set by Plug: https://github.com/elixir-plug/plug/blob/master/lib/plug/session.ex#L85

**Comment by jeffkreeftmeijer** [comment]
Hey @mbuhot,

Thanks a lot for bringing this to our attention. You’re right, this should have been `:done`, there. I’ve just released version 2.0.3 which should resolve this issue. Could you upgrade `:appsignal_plug` in your project `mix deps.update appsignal_plug`, and let me know if it resolved this issue for you?
